name: firefirestyle
description: web client
version: 0.0.1
dependencies:
 browser: any
 dart.html.location:
   git:
     url: https://github.com/firefirestyle/dart.html.location.git
 dart.httprequest:
   git:
     url: https://github.com/firefirestyle/dart.httprequest.git
 dart_to_js_script_rewriter: any
transforms:
- dart_to_js_script_rewriter
