name: firefirestyle
description: web client
version: 0.0.1
dependencies:
 browser: any
 cookie: any
 crypto: any
 firefirestyle.html.location:
   git:
     url: https://github.com/firefirestyle/dart.html.location.git
 firefirestyle.httprequest:
   git:
     url: https://github.com/firefirestyle/dart.httprequest.git
 firefirestyle.miniprop:
   git:
     url: https://github.com/firefirestyle/dart.miniprop.git
 firefirestyle.textbuilder:
   git:
     url: https://github.com/firefirestyle/dart.textbuilder.git
 firefirestyle.dialog:
   path: ../dart.dialog
 dart_to_js_script_rewriter: any
transforms:
- dart_to_js_script_rewriter
