name: firefirestyle.cl
description: web client
version: 0.0.1
dependencies:
 browser: any
 cookie: any
 crypto: any
 firefirestyle.location:
   git:
     url: https://github.com/firefirestyle/dart.location.git
 firefirestyle.html.page:
   git:
     url: https://github.com/firefirestyle/dart.html.page.git
 firefirestyle.httprequest:
   git:
     url: https://github.com/firefirestyle/dart.httprequest.git
 firefirestyle.miniprop:
   git:
     url: https://github.com/firefirestyle/dart.miniprop.git
 firefirestyle.textbuilder:
   git:
     url: https://github.com/firefirestyle/dart.textbuilder.git
 firefirestyle.dialog:
   path: ../dart.dialog
 firefirestyle.cl.netbox:
   git:
     url: https://github.com/firefirestyle/appspot.cl.netbox.git
 firefirestyle.dynamicblock:
   path: ../dart.dynamicblock
 dart_to_js_script_rewriter: any
transforms:
- dart_to_js_script_rewriter
